require_relative 'overpromotion/board'
require_relative 'overpromotion/game'
require_relative 'overpromotion/move_executor'
require_relative 'overpromotion/move_validator'
require_relative 'overpromotion/stone'
